#!/usr/bin/env node
// Generated by scripts/validate-packs.mjs
// Run: node packages/core/scripts/validate-packs.mjs

import { readFileSync, writeFileSync, readdirSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const distDir = resolve(__dirname, "../dist");
const testFixturesDir = resolve(__dirname, "../test/fixtures");
const docsDir = resolve(__dirname, "../../../docs");

const { PACK_COVERAGE } = await import(join(distDir, "pack-coverage.js"));
const { runHeuristicReview } = await import(join(distDir, "heuristics.js"));

// Pack id -> vulnerable fixture files (excluding clean fixtures)
const PACK_VULNERABLE_FIXTURES = {
  solana: [
    "unchecked-account.diff",
    "raw-cpi.diff",
    "remaining-accounts.diff",
    "cpi-program-unpinned.diff",
    "skip-preflight.diff",
    "unconfirmed-transaction.diff",
    "blockhash-expiry.diff",
    "signature-only-confirmation.diff",
    "deprecated-blockhash.diff",
    "panic.diff",
    "non-canonical-bump.diff",
    "manual-close.diff",
    "unvalidated-token.diff",
    "token-2022-extension.diff",
    "unchecked-arithmetic.diff",
    "authority-invariant.diff",
    "hardcoded-keypair.diff",
    "constraint-removed.diff",
    "constraint-weakened.diff",
    "invariant-removed.diff"
  ],
  evm: [
    "tx-origin.diff",
    "delegatecall.diff",
    "selfdestruct.diff",
    "assembly.diff",
    "block-timestamp.diff",
    "unbounded-loop.diff",
    "floating-pragma.diff",
    "ether-call.diff",
    "unchecked-call.diff",
    "unchecked-erc20.diff"
  ],
  iac: [
    "public-acl.diff",
    "open-ingress.diff",
    "encryption-disabled.diff",
    "public-ip.diff",
    "hardcoded-secret.diff",
    "privileged.diff",
    "host-namespace.diff",
    "run-as-root.diff",
    "privilege-escalation.diff",
    "latest-tag.diff"
  ],
  llm: [
    "prompt-interpolation.diff",
    "output-to-eval.diff",
    "output-to-html.diff",
    "tool-args.diff",
    "hardcoded-key.diff",
    "prompt-logged.diff",
    "moderation-off.diff",
    "pii-in-prompt.diff",
    "authz-from-model.diff",
    "external-into-prompt.diff"
  ],
  move: [
    "public-entry.diff",
    "borrow-global-mut.diff",
    "move-from.diff",
    "shared-object.diff",
    "copy-ability.diff",
    "downcast.diff",
    "privileged-fun.diff",
    "vector-borrow.diff",
    "drop-key.diff",
    "init-entrypoint.diff"
  ],
  ci: [
    "pull-request-target.diff",
    "expression-injection.diff",
    "unpinned-action.diff",
    "broad-permissions.diff",
    "self-hosted.diff",
    "pr-head-checkout.diff",
    "install-script.diff",
    "hardcoded-token.diff",
    "pipe-to-shell.diff",
    "docker-latest.diff"
  ],
  fintech: [
    "float-money.diff",
    "card-in-logs.diff",
    "card-literal.diff",
    "cvv-stored.diff",
    "webhook-unverified.diff",
    "float-math.diff",
    "pii-plaintext.diff",
    "tls-disabled.diff",
    "currency-rounding.diff",
    "sql-concat.diff"
  ],
  web: [
    "ssrf.diff",
    "command-injection.diff",
    "path-traversal.diff",
    "reflected-xss.diff",
    "open-redirect.diff",
    "mass-assignment.diff",
    "cors-wildcard.diff",
    "csrf-disabled.diff",
    "insecure-deserialization.diff",
    "weak-crypto.diff"
  ],
  healthcare: [
    "phi-in-logs.diff",
    "phi-plaintext.diff",
    "phi-in-url.diff",
    "phi-to-external.diff",
    "phi-in-response.diff",
    "phi-to-analytics.diff",
    "patient-idor.diff",
    "clinical-credential.diff",
    "broad-phi-query.diff",
    "weak-phi-encryption.diff"
  ],
  mobile: [
    "insecure-storage.diff",
    "hardcoded-secret.diff",
    "cleartext-traffic.diff",
    "exported-component.diff",
    "webview-js.diff",
    "tls-disabled.diff",
    "sensitive-logging.diff",
    "debuggable.diff",
    "insecure-random.diff",
    "keychain-accessibility.diff"
  ],
  accessibility: [
    "anchor-with-empty-or-placeholder-href-used-as-a-bu.diff",
    "autoplaying-media-that-is-not-muted.diff",
    "click-handler-on-non-interactive-element-without-r.diff",
    "form-input-relies-on-placeholder-instead-of-a-labe.diff",
    "heading-level-skipped-h1-directly-to-h3.diff",
    "icon-only-button-without-an-accessible-name.diff",
    "image-missing-alt-attribute.diff",
    "misspelled-or-invalid-aria-attribute.diff",
    "positive-tabindex-value-disrupts-focus-order.diff",
    "root-html-element-missing-lang-attribute.diff"
  ],
  "data-sql": [
    "cartesian-or-cross-join-that-explodes-row-counts.diff",
    "drop-or-truncate-table-without-an-existence-or-env.diff",
    "float-or-real-used-for-a-monetary-column.diff",
    "hardcoded-database-connection-string-or-dsn.diff",
    "multiple-dependent-writes-executed-without-a-trans.diff",
    "pii-column-selected-into-logs-or-printed-output.diff",
    "select-used-in-a-production-query.diff",
    "sql-query-built-by-string-concatenation-or-f-strin.diff",
    "unbounded-query-missing-a-limit-clause.diff",
    "update-or-delete-statement-missing-a-where-clause.diff"
  ],
  k8s: [
    "container-allowed-to-run-as-root.diff",
    "container-missing-resource-limits.diff",
    "container-runs-as-uid-0-root.diff",
    "dangerous-linux-capability-added.diff",
    "host-namespace-sharing-enabled.diff",
    "mutable-latest-image-tag.diff",
    "privilege-escalation-allowed.diff",
    "privileged-container-in-securitycontext.diff",
    "rbac-rule-grants-wildcard-access.diff",
    "service-account-token-automounted.diff"
  ],
  privacy: [
    "analytics-fired-before-consent.diff",
    "cookie-set-without-consent-gating.diff",
    "full-pii-table-dumped.diff",
    "pii-in-url-query-string.diff",
    "pii-sent-to-analytics-ml-without-anonymisation.diff",
    "pii-shared-with-third-party-without-contract-flag.diff",
    "pii-stored-without-retention-ttl.diff",
    "pii-written-to-logs.diff",
    "precise-geolocation-captured-without-notice.diff",
    "soft-delete-used-instead-of-right-to-erasure.diff"
  ],
  mlops: [
    "data-leakage-scaler-transform-fit-before-train-tes.diff",
    "eval-exec-on-experiment-config-or-hyperparameters.diff",
    "hardcoded-dataset-registry-storage-credentials.diff",
    "model-trained-on-full-dataset-with-no-train-test-s.diff",
    "no-random-seed-set-training-is-non-reproducible.diff",
    "target-identifier-leakage-column-kept-in-training-.diff",
    "torch-load-called-without-weights-only-true.diff",
    "unpinned-model-dataset-download-from-hub.diff",
    "unsafe-yaml-load-for-experiment-pipeline-config.diff",
    "untrusted-model-artifact-deserialized-via-pickle-t.diff"
  ],
  embedded: [
    "allocation-result-used-without-null-check.diff",
    "dynamic-allocation-via-new-on-a-real-time-isr-path.diff",
    "floating-point-equality-comparison.diff",
    "hardware-register-isr-shared-variable-missing-vola.diff",
    "ignored-return-value-of-a-system-library-call.diff",
    "magic-buffer-size-literal-in-array-declaration.diff",
    "memcpy-memmove-with-an-unchecked-length.diff",
    "signed-unsigned-comparison-mismatch-in-loop-bound.diff",
    "unbounded-string-operation-strcpy-strcat-sprintf-g.diff",
    "use-of-goto.diff"
  ],
  performance: [
    "await-inside-a-loop-serialized-i-o.diff",
    "database-query-inside-a-loop-n-1.diff",
    "json-parse-of-an-unbounded-request-body.diff",
    "list-endpoint-missing-pagination-limit.diff",
    "new-db-connection-per-request-no-pool.diff",
    "o-n-2-nested-includes-indexof-scan.diff",
    "outbound-fetch-axios-without-a-timeout.diff",
    "setinterval-without-cleanup-handle-leak.diff",
    "synchronous-fs-call-in-a-request-path.diff",
    "unbounded-in-memory-accumulator-growth.diff"
  ],
  graphql: [
    "graphql-introspection-enabled-in-production.diff",
    "list-resolver-causes-n-1-queries-no-dataloader.diff",
    "missing-query-depth-complexity-limit.diff",
    "mutation-type-without-rate-limit-directive.diff",
    "privileged-resolver-missing-object-field-level-aut.diff",
    "query-batching-amplification-enabled.diff",
    "raw-database-query-built-from-graphql-args.diff",
    "skip-include-used-to-bypass-auth-protected-field.diff",
    "unbounded-list-pagination-argument.diff",
    "verbose-graphql-error-leaks-internals.diff"
  ]
};

const PACK_CLEAN_FIXTURES = {
  solana: ["clean-anchor.diff", "clean-web3.diff", "clean-token-2022-validated.diff"],
  evm: ["clean-solidity.diff"],
  iac: ["clean-iac.diff"],
  llm: ["clean-llm.diff"],
  move: ["clean-move.diff"],
  ci: ["clean-ci.diff"],
  fintech: ["clean-fintech.diff"],
  web: ["clean-web.diff"],
  healthcare: ["clean-healthcare.diff"],
  mobile: ["clean-mobile.diff"],
  // New packs rely on the shared cross-domain benign/ corpus rather than
  // per-pack clean fixtures.
  accessibility: [],
  "data-sql": [],
  k8s: [],
  privacy: [],
  mlops: [],
  embedded: [],
  performance: [],
  graphql: []
};

function readFixture(packDir, name) {
  return readFileSync(join(packDir, name), "utf8");
}

function detectPackTitles(packId, fixtureFiles, packDir) {
  const knownTitles = new Set(PACK_COVERAGE[packId].map((e) => e.title));
  const detected = new Set();
  for (const file of fixtureFiles) {
    const diff = readFixture(packDir, file);
    const result = runHeuristicReview({ mode: "review", subject: "t", diff });
    for (const finding of result.findings) {
      if (knownTitles.has(finding.title)) {
        detected.add(finding.title);
      }
    }
  }
  return detected;
}

// Collect benign fixture paths
const benignDir = join(testFixturesDir, "benign");
const benignFiles = readdirSync(benignDir).filter((f) => f.endsWith(".diff"));

// Per-pack results
const packResults = {};
let totalFalsePositives = 0;
let totalClasses = 0;
let totalDetected = 0;

for (const [packId, entries] of Object.entries(PACK_COVERAGE)) {
  const packDir = join(testFixturesDir, packId);
  const vulnFixtures = PACK_VULNERABLE_FIXTURES[packId];
  const cleanFixtures = PACK_CLEAN_FIXTURES[packId];

  const detectedTitles = detectPackTitles(packId, vulnFixtures, packDir);

  // Check clean fixtures for false positives
  const knownTitles = new Set(entries.map((e) => e.title));
  let packFalsePositives = 0;
  for (const cleanFile of cleanFixtures) {
    const diff = readFixture(packDir, cleanFile);
    const result = runHeuristicReview({ mode: "review", subject: "t", diff });
    for (const finding of result.findings) {
      if (knownTitles.has(finding.title)) {
        packFalsePositives++;
        console.error(`[FP] ${packId}/${cleanFile}: "${finding.title}"`);
      }
    }
  }

  packResults[packId] = {
    entries,
    detectedTitles,
    total: entries.length,
    detected: detectedTitles.size,
    falsePositives: packFalsePositives
  };

  totalFalsePositives += packFalsePositives;
  totalClasses += entries.length;
  totalDetected += detectedTitles.size;
}

// Check benign fixtures across all packs
let benignFalsePositives = 0;
const allKnownTitles = new Set(
  Object.values(PACK_COVERAGE).flatMap((entries) => entries.map((e) => e.title))
);
for (const benignFile of benignFiles) {
  const diff = readFixture(benignDir, benignFile);
  const result = runHeuristicReview({ mode: "review", subject: "t", diff });
  for (const finding of result.findings) {
    if (allKnownTitles.has(finding.title)) {
      benignFalsePositives++;
      console.error(`[FP] benign/${benignFile}: "${finding.title}"`);
    }
  }
}
totalFalsePositives += benignFalsePositives;

// Build the markdown report
const packIds = Object.keys(PACK_COVERAGE);
const benignCount = benignFiles.length;

let md = `# Pack Validation Report

Generated by scripts/validate-packs.mjs

**Summary:** ${packIds.length} packs, ${totalClasses} classes, ${benignCount} cross-domain benign fixtures, ${totalFalsePositives} false positives

---

`;

for (const packId of packIds) {
  const { entries, detectedTitles, total, detected, falsePositives } = packResults[packId];
  md += `## Pack: \`${packId}\` — ${detected}/${total} detected`;
  if (falsePositives > 0) {
    md += ` (${falsePositives} false positive${falsePositives > 1 ? "s" : ""})`;
  }
  md += "\n\n";
  md += `| Class | Standard | Reference | Detected |\n`;
  md += `| ----- | -------- | --------- | -------- |\n`;
  for (const entry of entries) {
    const tick = detectedTitles.has(entry.title) ? "yes" : "no";
    md += `| ${entry.title} | ${entry.standard} | ${entry.reference} | ${tick} |\n`;
  }
  md += "\n";
}

md += `---

## Methodology

Findings are produced by **deterministic diff heuristics** — each class maps a
known-bad pattern (regex or structural match) to a confirmed vulnerable fixture
and a recognised security taxonomy entry. The demo corpus combines pack-specific
vulnerable fixtures, pack-specific clean fixtures for packs that define them, and
${benignCount} cross-domain benign fixtures into a repeatable regression suite.
A real AI council (LLM-based review) can be layered on top of these heuristics
for richer, context-sensitive analysis.
`;

writeFileSync(join(docsDir, "PACK-VALIDATION.md"), md, "utf8");

console.error(
  `[validate-packs] ${packIds.length} packs, ${totalClasses} classes, ${totalDetected}/${totalClasses} detected, ${totalFalsePositives} false positives — report written to docs/PACK-VALIDATION.md`
);
