export type RegressionState = "verified" | "contradicted" | "inconclusive";
export type RegressionReason = "reproduced-and-fixed" | "not-reproduced" | "not-fixed" | "unexpected-failure" | "setup-failed" | "environment-delta" | "missing-assertion" | "duplicate-assertion" | "skipped-assertion" | "invalid-output" | "incomplete-output" | "timeout" | "cancelled" | "input-mutated" | "cleanup-failed" | "unsupported-runner" | "unsupported-platform" | "unsupported-config" | "invalid-input";
export type RegressionPhase = "preflight" | "setup" | "base" | "head" | "cleanup";
export interface RegressionIssue { reason: RegressionReason; phase: RegressionPhase; detail: string }
export interface RegressionObservation { execution: "complete" | "incomplete"; assertionStatus: "passed" | "failed" | "missing" | "duplicate" | "skipped"; expectedFailureMatched: boolean; exitCode: number | null; issues: RegressionIssue[] }
export interface RegressionDecision { state: RegressionState; reason: RegressionReason; issues: RegressionIssue[] }
export interface RegressionManifest { schemaVersion: 1; id: string; base: string; head: string; runner: "vitest"; testFiles: string[]; supportFiles: string[]; assertion: {fullName:string;expectedFailureText:string}; setupArgv?:string[]; runArgv:string[]; timeoutMs:number; setupTimeoutMs:number; maxOutputBytes:number }
export interface BoundedCommandResult { exitCode:number|null; timedOut:boolean; aborted:boolean; stdout:{text:string;truncated:boolean}; stderr:{text:string;truncated:boolean}; cleanupFailed:boolean; durationMs:number }
export interface ResolvedRegressionInput { sourceRoot:string; baseSha:string; headSha:string; sourceFingerprint:string; manifestDigest:string; bundleDigest:string; environmentDigest:string; nodeVersion:string; manifest:RegressionManifest; assets:Array<{path:string;bytes:Buffer;sha256:string}>; issues:RegressionIssue[] }
export interface RegressionExecutionRecord { phase:"setup"|"base"|"head"; target:"base"|"head"; argv:string[]; result:BoundedCommandResult; fingerprint:string; runnerVersion:string|null; observation?:RegressionObservation }
export interface RegressionRunResult { input:ResolvedRegressionInput; decision:RegressionDecision; executions:RegressionExecutionRecord[]; startedAt:string; finishedAt:string; durationMs:number }
export interface RegressionReport { schemaVersion:1;kind:"regression";id:string;baseSha:string;headSha:string;sourceFingerprint:string;manifestDigest:string;bundleDigest:string;environmentDigest:string;nodeVersion:string;decision:RegressionDecision;executions:RegressionExecutionRecord[];startedAt:string;finishedAt:string;durationMs:number;trustMode:"local-assertion";producer:"quorate-local";artifactHash:string;signature:string }
