import { Link } from "react-router-dom";
import { CodeBlock } from "./CodeBlock";
import { InlineCode } from "./InlineCode";
import type { PackDocData } from "../lib/pack-docs";

const ACTION_REF = "UmutKorkmaz/quorate@v0.7.2";

/**
 * Renders a full domain-pack documentation article from a {@link PackDocData}
 * record. Every pack page added beyond the crypto/web3 core shares this layout,
 * so prose and structure stay consistent while the data table drives content.
 */
export function PackDocTemplate({ data }: { data: PackDocData }) {
  const roles = data.councils.map((c) => c.role).join(", ");

  return (
    <article className="doc-page">
      <h1>{data.label}</h1>
      <p className="lead">{data.lead}</p>

      <h2>Set up</h2>
      <p>
        Run <InlineCode>quorate init</InlineCode> with the {data.label} pack to scaffold the
        config and role guidance in your repo:
      </p>
      <CodeBlock language="bash">{`quorate init --pack ${data.id}`}</CodeBlock>
      <p>
        This writes a <InlineCode>.quorate.yml</InlineCode> with councils tuned for{" "}
        {data.standard} review:
      </p>
      <ul>
        {data.councils.map((council) => (
          <li key={council.role}>
            <strong>{council.role}</strong> — {council.description}
          </li>
        ))}
      </ul>
      <p>
        Each council role ships with reviewer guidance tuned to the {data.label} threat model.
        Run <InlineCode>quorate packs</InlineCode> to see every available pack and its bundled
        councils.
      </p>

      <h2>What it catches</h2>
      <p>
        The heuristic reviewer runs with zero setup — no model, no API key, no CLI install. It
        scans every added line in the diff against ten {data.standard} vulnerability classes. A
        real council (claude, codex, or any <InlineCode>type: api</InlineCode> model) then layers
        semantic review on top using the pack&apos;s role guidance.
      </p>
      <table>
        <thead>
          <tr>
            <th>Heuristic</th>
            <th>Severity</th>
            <th>What it flags</th>
          </tr>
        </thead>
        <tbody>
          {data.heuristics.map((h) => (
            <tr key={h.title}>
              <td>
                <strong>{h.title}</strong>
              </td>
              <td>
                <InlineCode>{h.severity}</InlineCode>
              </td>
              <td>{h.flags}</td>
            </tr>
          ))}
        </tbody>
      </table>
      <p>
        A heuristic-only review is reported as <strong>degraded</strong> — an honest WARN, never a
        confident green. Add a council provider to get full semantic coverage.
      </p>

      <h2>On every PR</h2>
      <p>
        Commit the <InlineCode>.quorate.yml</InlineCode> scaffolded by{" "}
        <InlineCode>quorate init --pack {data.id}</InlineCode> to your base branch, add the
        workflow below, and set <InlineCode>OPENROUTER_API_KEY</InlineCode> in your repository
        secrets. The workflow uses <InlineCode>runner-mode: api</InlineCode> so it runs on a
        standard GitHub-hosted runner — no self-hosted machine needed.
      </p>
      <CodeBlock language="yaml">{`# .quorate.yml (base branch — generated by quorate init --pack ${data.id})
providers:
  - id: heuristic
    type: mock
    enabled: true
  - id: openrouter
    type: api
    enabled: true
    baseUrl: https://openrouter.ai/api/v1
    model: anthropic/claude-sonnet-4.6
    apiKeyEnv: OPENROUTER_API_KEY
    roles: [${roles}]`}</CodeBlock>
      <CodeBlock language="yaml">{`name: Quorate — ${data.label} review
on: pull_request
permissions:
  contents: read
  pull-requests: write
jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ${ACTION_REF}
        env:
          OPENROUTER_API_KEY: \${{ secrets.OPENROUTER_API_KEY }}
        with:
          github-token: \${{ secrets.GITHUB_TOKEN }}
          runner-mode: api`}</CodeBlock>
      <p>
        The heuristic always runs regardless of <InlineCode>runner-mode</InlineCode>. Swap the
        OpenRouter model for any OpenAI-compatible endpoint — see{" "}
        <Link to="/docs/providers">Providers</Link> for presets and the{" "}
        <InlineCode>quorate provider add</InlineCode> command. For general Action options (inline
        comments, <InlineCode>fail-on</InlineCode>, agreement gate) see{" "}
        <Link to="/docs/github-action">GitHub Action</Link>.
      </p>
    </article>
  );
}
