import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

export interface CommandDocRow {
  name: string;
  summary: string;
  argHint?: string;
  aliases?: string[];
  hidden?: boolean;
}

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const COMMANDS_SOURCE = join(ROOT, "packages/cli/src/tui/commands.ts");
const OUTPUT_PATH = join(ROOT, "packages/website/src/generated/commands.md");

const REGISTRY_MARKERS = ["export const baseCommandRegistry", "export const commandRegistry"];

/** Extract registry entries from the CLI source (no runtime import). */
export function parseCommandRegistry(source: string): CommandDocRow[] {
  const marker = REGISTRY_MARKERS.find((candidate) => source.includes(candidate));
  if (!marker) {
    throw new Error(
      `command registry not found in ${COMMANDS_SOURCE} (expected one of: ${REGISTRY_MARKERS.join(", ")})`
    );
  }
  const start = source.indexOf(marker);

  const arrayStart = source.indexOf("[", start);
  const arrayEnd = source.indexOf("\n];", arrayStart);
  if (arrayStart < 0 || arrayEnd < 0) {
    throw new Error("Could not locate commandRegistry array bounds");
  }

  const arrayBody = source.slice(arrayStart + 1, arrayEnd);
  const chunks = arrayBody
    .split(/\n  \},\n  \{/)
    .map((chunk, index, all) => {
      if (all.length === 1) return chunk;
      if (index === 0) return `${chunk}\n  }`;
      if (index === all.length - 1) return `{\n  ${chunk}`;
      return `{\n  ${chunk}\n  }`;
    });

  const commands: CommandDocRow[] = [];
  for (const chunk of chunks) {
    const name = chunk.match(/name:\s*"([^"]+)"/)?.[1];
    const summary = chunk.match(/summary:\s*"([^"]+)"/)?.[1];
    if (!name || !summary) continue;

    const argHint = chunk.match(/argHint:\s*"([^"]+)"/)?.[1];
    const hidden = /\bhidden:\s*true\b/.test(chunk);
    const aliasMatch = chunk.match(/aliases:\s*\[([^\]]*)\]/);
    const aliases = aliasMatch
      ? [...aliasMatch[1].matchAll(/"([^"]+)"/g)].map((match) => match[1])
      : undefined;

    commands.push({ name, summary, argHint, aliases, hidden });
  }

  return commands;
}

function escapeMarkdownCell(text: string): string {
  return text.replace(/\|/g, "\\|").replace(/\n/g, " ");
}

function formatCommandCell(row: CommandDocRow): string {
  const args = row.argHint ? ` ${row.argHint}` : "";
  const base = `\`/${row.name}${args}\``;
  if (!row.aliases?.length) return base;
  const aliasText = row.aliases.map((alias) => `\`${alias}\``).join(", ");
  return `${base} (${aliasText})`;
}

export function renderCommandsMarkdown(rows: CommandDocRow[]): string {
  const visible = rows.filter((row) => !row.hidden);
  const seen = new Set<string>();
  const unique = visible.filter((row) => {
    if (seen.has(row.name)) return false;
    seen.add(row.name);
    return true;
  });

  return [
    "<!-- Auto-generated by scripts/generate-command-docs.ts. Do not edit. -->",
    "",
    "# Shell commands",
    "",
    "Type `/` in the Quorate interactive shell to open the command palette.",
    "",
    "| Command | Description |",
    "| --- | --- |",
    ...unique.map((row) => `| ${formatCommandCell(row)} | ${escapeMarkdownCell(row.summary)} |`),
    ""
  ].join("\n");
}

function main(): void {
  const source = readFileSync(COMMANDS_SOURCE, "utf8");
  const rows = parseCommandRegistry(source);
  const markdown = renderCommandsMarkdown(rows);

  mkdirSync(dirname(OUTPUT_PATH), { recursive: true });
  writeFileSync(OUTPUT_PATH, markdown, "utf8");

  const visibleCount = rows.filter((row) => !row.hidden).length;
  console.log(`Wrote ${visibleCount} shell commands to ${OUTPUT_PATH}`);
}

main();